#!/bin/bash
echo "🚀 QUICK SETUP FOR OPENBOX"
echo "========================================"

echo ""
echo "Step 1: Add GitHub Secrets"
echo "========================================"
echo "Go to: https://github.com/OrgHide/openbox/settings/secrets/actions"
echo ""
echo "Add these secrets:"
echo ""
echo "Secret 1:"
echo "  Name: DEPLOY_KEY"
echo "  Value: $(cat ~/openbox/deploy/openbox-deploy-key)"
echo ""
echo "Secret 2:"
echo "  Name: NORTHFLANK_TOKEN"
echo "  Value: nf-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNzYzMmJkMGMtNDdhYy00MjhhLTg2ZjEtNWU5ODI4MzI2MWEyIiwiZW50aXR5SWQiOiI2YTQxYzk3Mjc5ZGU1OWEyMWRlMTFkN2IiLCJlbnRpdHlUeXBlIjoidGVhbSIsInRva2VuSWQiOiI2YTQ0MjZlNmJlNmYwMjk1MzgyMGVlMWIiLCJ0b2tlbkludGVybmFsSWQiOiJ0ZXJtdXgiLCJyb2xlSWQiOiI2YTQxYzk3Mjc5ZGU1OWEyMWRlMTFkN2MiLCJyb2xlRW50aXR5SWQiOiI2YTQxYzk3Mjc5ZGU1OWEyMWRlMTFkN2IiLCJyb2xlRW50aXR5VHlwZSI6InRlYW0iLCJyb2xlSW50ZXJuYWxJZCI6Im93bmVyIiwidHlwZSI6InJiYWMiLCJpYXQiOjE3ODI4NTEzMDJ9.WEfgZ6wMYsdsKv8S8a58FYxSj7h1hJou6E6M67JuYAo"
echo ""

echo "Step 2: Add Deploy Keys"
echo "========================================"
echo "GitHub Deploy Key:"
echo "  URL: https://github.com/OrgHide/openbox/settings/keys"
echo "  Title: OpenBox Deploy Key"
echo "  Key: $(cat ~/openbox/deploy/openbox-deploy-key.pub)"
echo ""
echo "Northflank SSH Key:"
echo "  URL: https://app.northflank.com/settings/ssh"
echo "  Title: OpenBox Northflank"
echo "  Key: $(cat ~/openbox/deploy/northflank-deploy-key.pub)"
echo ""

echo "Step 3: Push to GitHub"
echo "========================================"
echo "cd ~/openbox"
echo "git add ."
echo "git commit -m 'OpenBox with GitHub Actions + Northflank'"
echo "git push origin main"
echo ""

echo "Step 4: Verify Deployment"
echo "========================================"
echo "Check: https://github.com/OrgHide/openbox/actions"
echo "Check: https://openbox.northflank.com"
