# Northflank Secrets for Tailscale Integration
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-secrets
  project: openbox
type: Opaque
data:
  # Base64 encoded values
  TAILSCALE_AUTH_KEY: dHNrZXktYXV0aC1rY1FlWUROa1YzMTFDTlRSTC1jSm5kSkZwdk1MRW5NUmoyVUFLWUtFd1N2Unh0Q21LdA==
  TAILSCALE_API_KEY: dHNrZXktYXBpLWtxRER4QzhZa2sxMUNOVFJMLXcyUDdRTHNhbWo4ZEhqd2hqZ0piazhYd0dNOUFFajhCZT09
  NORTHFLANK_TOKEN: bmYtZXlKaGJHY2lPaUpJVXpWMWZIUnZJaXdpWjI5ZmRIbHVaWFFpT2lJMk5qTXpNa3hpTURNdE5EUmhZeTAwTWpobExUZzJaakV0TldVNU9ESTRNekkyTVdFeUlpd2laRzFoZEdsdmJpSTZJbVl4TVRReVp6azNNamM1WkdVNU9XRTJNV1JsTVRGa05pSWlMQ0psYm1GamRHOXlYVkJpYmlJNkluVmhZbTVzTGlJc0lHWnZjbTFoZEdsdmJpSTZJbVl4TlRReVp6azNNamM1WkdVNU9XRTJNV1JsTVRGa05pSWlMQ0psY205dmRYSnBibWNpT2lKMFpYUmxNaUlzSW1Sb2JYUWlPaUkyWVRRMFpqbGxObUpsTm1Zd01qa3hNemd5TUdWbE1URmtOa2tpTENKbGJXRnBiM0lpT2lJNllUUXhZemszTWpjNVpHVTVPV0UyTVdSbE1URmtOa2lpTENKcGJYQnZjblJpY3lJNkluVmlhMFlpTENKbmIyOW5iM1JpY3lJNkluVmlZVzBpTENKcGJuUmxjbWx1WnlJNkluWnZjbTFoZEd4bGJuUWlMQ0p6ZFdJdWIzVmlaWEp6SWpwYkltOTNiblJwYldVaUxDSnpkV0l1Ykc5allXeGxjaUk2SW05M2JuUnBiV1VpTENKcGJYQnZjblJpTm1JdVpIVmliQ0k2SW14cGJtVmxaQ0o5LldFZmdaNndNWXNkc0t2OFM4YTU4Rll4U2o3aDFoSm91NkU2TTY3SnVZQW8=
